### ISSUE TITLE
CUSA03173 (and others) - Bloodborne

### ISSUE THREAD

**Issue by xzyxzy** [shadps4-emu/ps4_cheats#2]
Added more patches from other source and additional resolution options with non 16:9 aspect ratios.

![image](https://github.com/user-attachments/assets/6554bde4-779c-4a5e-ad88-465a1f3891ae)

Can't attach XML so ZIP in attachments.

[Bloodborne-Orbis.zip](https://github.com/user-attachments/files/16805336/Bloodborne-Orbis.zip)

Edit: removed `isEnabnled`, added few notes.

**Comment by DanielSvoboda** [comment]
you can try adding this file to that folder:
https://github.com/shadps4-emu/ps4_cheats/tree/main/PATCHES

And make sure that all `isEnabled` are set to **false**, you don't actually need to add them, the emulator adds them, but since this file has them, set them all to false.

'Note' is not mandatory, but it is good to explain what the specific 'patch' does.

Check if the author names are correct for these new patches, is `Author=xyz` the name of the person who made this?

**Comment by DanielSvoboda** [comment]
I made this PR https://github.com/shadps4-emu/ps4_cheats/pull/5 to add what you put:


Have you tested them all?
```
Unlock Game Region
Bookmark and Capture outputs

Resolution Patch (864x486)
Resolution Patch (2560x1440)
Resolution Patch (3200x1800)
Resolution Patch (3840x2160)
Resolution Patch (1280x800) (16:10)
Resolution Patch (2560x1080) (21:9 2.37)
Resolution Patch (3440x1440) (21:9 2.38)
Resolution Patch (3840x1080) (32:9 ~3.55)
Resolution Patch (1280x960) (4:3 ~1.33)
```

**Comment by Foul-Tarnished** [comment]
imo you should add 4K for 3840x2160, and 2K for 2560x1440

Also, I don't think the aspect ratio decimal value is interesting (keep 4:3 but remove ~1.33)

**Comment by Foul-Tarnished** [comment]
Would be better if we could have a textbox to entee the width and height instead of having dozens od patches for each different resolution

so we would have 720p, 2k, 4k, 2k widescreen, 4k widescreen, and then a custom one where we can enter our own values.

I mean in the GUI directly, I know we can edit the file and set any value, but its way less convenient

**Comment by DanielSvoboda** [comment]
Currently the emulator can apply multiple files at the same time, one solution would be to place a separate patch file just for resolutions 
![image](https://github.com/user-attachments/assets/fa4180aa-1722-4576-93bc-8137090218c4)

**Comment by DanielSvoboda** [comment]
I separated them, if you want to make any corrections:
https://github.com/DanielSvoboda/ps4_cheats/blob/main/PATCHES/Bloodborne-Resolution.xml

**Comment by Foul-Tarnished** [comment]
I mean there are infinite possibilities, so even then we would see dozens
or more

Le dim. 1 sept. 2024, 02:40, DanielSvoboda ***@***.***> a
écrit :

**Comment by xzyxzy** [comment]
> I made this PR #5 to add what you put:
> 
> Have you tested them all?
> 
> ```
> Unlock Game Region
> Bookmark and Capture outputs
> 
> Resolution Patch (864x486)
> Resolution Patch (2560x1440)
> Resolution Patch (3200x1800)
> Resolution Patch (3840x2160)
> Resolution Patch (1280x800) (16:10)
> Resolution Patch (2560x1080) (21:9 2.37)
> Resolution Patch (3440x1440) (21:9 2.38)
> Resolution Patch (3840x1080) (32:9 ~3.55)
> Resolution Patch (1280x960) (4:3 ~1.33)
> ```

I retested only resolution patches since I am the author of these, except 3840x2160 since my gpu don't have enough vram. This (4k) cheat was tested by very few people who have 4090 on older builds with py-patcher.

Other two cheats was asked to be added by some guy on discord and been just copied and pasted.

All these work except 21:9 and 32:9 exhibit mild enemy hp bar misalignment when target is way off-center.

**Comment by DanielSvoboda** [comment]
ready, it was added

**Comment by rochobadge** [comment]
please add a 5120p x 1440p option

**Comment by jaimeanime** [comment]
How can I make the ultra wide patches for the other games?

**Comment by DanielSvoboda** [comment]
> How can I make the ultra wide patches for the other games?

There are some instructions on the repository's home page, and you can also find a video on YouTube explaining a little more about reverse engineering and creating cheats for PS4. Or you can join the GoldHEN discord, which has many people who understand the subject and can help you.
![image](https://github.com/user-attachments/assets/e08bc66d-b8ba-44d9-9631-19d3d2243535)
